import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { connectDB } from "@/lib/db";
import { requireUser } from "@/lib/session";
import Transaction from "@/models/Transaction";
import Person from "@/models/Person";
import { activeQuery } from "@/lib/bin";

function money(value) {
  return Number(value || 0).toFixed(2);
}

function short(text, max = 42) {
  const str = String(text || "");
  return str.length > max ? `${str.slice(0, max - 1)}...` : str;
}

export async function GET() {
  const { user, error } = await requireUser();
  if (error) return error;

  await connectDB();
  const tx = await Transaction.find({ userId: user._id, ...activeQuery() }).populate("personId", "name").sort({ date: -1 });

  const totalCredit = tx
    .filter((item) => item.type === "credit")
    .reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const totalDebit = tx
    .filter((item) => item.type === "debit")
    .reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const pendingCount = tx.filter((item) => item.status === "pending").length;

  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const width = 595;
  const height = 842;
  const margin = 40;
  const contentWidth = width - margin * 2;
  const rowHeight = 22;

  let page = pdfDoc.addPage([width, height]);
  let y = height - margin;

  const drawHeader = () => {
    page.drawRectangle({ x: margin, y: y - 64, width: contentWidth, height: 64, color: rgb(0.07, 0.07, 0.07) });
    page.drawText("PERSONAL CREDIT/DEBIT MANAGER", {
      x: margin + 14,
      y: y - 24,
      size: 11,
      font: bold,
      color: rgb(1, 1, 1),
    });
    page.drawText("Premium Financial Report", {
      x: margin + 14,
      y: y - 42,
      size: 15,
      font: bold,
      color: rgb(1, 1, 1),
    });
    y -= 84;
  };

  const drawCard = (x, title, value) => {
    page.drawRectangle({ x, y: y - 56, width: 166, height: 56, color: rgb(0.96, 0.96, 0.96), borderWidth: 0.7, borderColor: rgb(0.85, 0.85, 0.85) });
    page.drawText(title, {
      x: x + 10,
      y: y - 20,
      size: 8,
      font,
      color: rgb(0.35, 0.35, 0.35),
    });
    page.drawText(value, {
      x: x + 10,
      y: y - 42,
      size: 13,
      font: bold,
      color: rgb(0.1, 0.1, 0.1),
    });
  };

  const drawTableHeader = () => {
    page.drawRectangle({ x: margin, y: y - rowHeight, width: contentWidth, height: rowHeight, color: rgb(0.08, 0.08, 0.08) });
    page.drawText("Person", { x: margin + 8, y: y - 15, size: 9, font: bold, color: rgb(1, 1, 1) });
    page.drawText("Type", { x: margin + 210, y: y - 15, size: 9, font: bold, color: rgb(1, 1, 1) });
    page.drawText("Amount", { x: margin + 265, y: y - 15, size: 9, font: bold, color: rgb(1, 1, 1) });
    page.drawText("Status", { x: margin + 355, y: y - 15, size: 9, font: bold, color: rgb(1, 1, 1) });
    page.drawText("Date", { x: margin + 430, y: y - 15, size: 9, font: bold, color: rgb(1, 1, 1) });
    y -= rowHeight;
  };

  const ensureSpace = (space = rowHeight) => {
    if (y - space < margin + 28) {
      page = pdfDoc.addPage([width, height]);
      y = height - margin;
      drawTableHeader();
    }
  };

  drawHeader();
  page.drawText(`Prepared for ${user.name} (${user.email})`, {
    x: margin,
    y,
    size: 9,
    font,
    color: rgb(0.35, 0.35, 0.35),
  });
  page.drawText(`Generated ${new Date().toLocaleString()}`, {
    x: margin + 290,
    y,
    size: 9,
    font,
    color: rgb(0.35, 0.35, 0.35),
  });
  y -= 18;

  drawCard(margin, "TOTAL CREDIT", money(totalCredit));
  drawCard(margin + 177, "TOTAL DEBIT", money(totalDebit));
  drawCard(margin + 354, "PENDING ENTRIES", String(pendingCount));
  y -= 70;

  drawTableHeader();

  tx.slice(0, 220).forEach((item, idx) => {
    ensureSpace();
    if (idx % 2 === 0) {
      page.drawRectangle({ x: margin, y: y - rowHeight, width: contentWidth, height: rowHeight, color: rgb(0.98, 0.98, 0.98) });
    }

    page.drawText(short(item.personId?.name || "Unknown", 26), { x: margin + 8, y: y - 15, size: 8.5, font, color: rgb(0.15, 0.15, 0.15) });
    page.drawText(item.type.toUpperCase(), { x: margin + 210, y: y - 15, size: 8.5, font: bold, color: rgb(0.15, 0.15, 0.15) });
    page.drawText(`${money(item.amount)} ${item.currency}`, { x: margin + 265, y: y - 15, size: 8.5, font, color: rgb(0.15, 0.15, 0.15) });
    page.drawText(item.status.toUpperCase(), { x: margin + 355, y: y - 15, size: 8.5, font, color: rgb(0.15, 0.15, 0.15) });
    page.drawText(new Date(item.date).toLocaleDateString(), { x: margin + 430, y: y - 15, size: 8.5, font, color: rgb(0.15, 0.15, 0.15) });
    y -= rowHeight;
  });

  page.drawText("Generated by Personal Credit/Debit Manager", {
    x: margin,
    y: 18,
    size: 8,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  const pdfBuffer = Buffer.from(await pdfDoc.save());

  return new Response(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=dues-report.pdf",
    },
  });
}
